name: mewayz
description: "Mewayz - All-in-One Business Platform for social media management, CRM, e-commerce, and more"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # Image handling
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Responsive design
  sizer: ^2.0.15
  
  # Storage & persistence
  shared_preferences: ^2.2.2
  
  # Networking
  dio: ^5.7.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  
  # Data visualization
  fl_chart: ^0.65.0
  
  # UI enhancement
  fluttertoast: ^8.2.4
  
  # Typography
  google_fonts: ^6.1.0
  
  # Internationalization
  intl: ^0.19.0

  # File handling
  file_picker: ^8.1.2

  # Additional dependencies for professional mobile app
  web: any
  crypto: any
  url_launcher: ^6.2.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Form Validation
  form_validator: ^1.0.0
  
  # UI Utilities
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Video Player
  video_player: ^2.8.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Social Media
  share_plus: ^7.2.1
  
  # Charts
  fl_chart: ^0.66.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Rich Text Editor
  flutter_quill: ^11.4.1
  
  # Animation
  animated_text_kit: ^4.2.2
  
  # Platform specific
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # App icons and launch images are automatically generated
  # by the flutter_launcher_icons package
  
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  
  # The following section is specific to Flutter packages.
  # https://flutter.dev/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21