version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mewayz-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mewayz-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mewayz-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mewayz
      - DATABASE_URL=mongodb://mongodb:27017/mewayz
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - PORT=8000
      - HOST=0.0.0.0
    networks:
      - mewayz-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: mewayz-mongodb
    restart: unless-stopped
    ports:
      - "5000:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=mewayz
    networks:
      - mewayz-network

volumes:
  mongodb_data:

networks:
  mewayz-network:
    driver: bridge