name: mewayz
description: "Comprehensive business platform for social media management, link-in-bio, e-commerce, courses, and more"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI Components
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Utilities
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Form Validation
  form_validator: ^1.0.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Device Info
  device_info_plus: ^10.1.0
  package_info_plus: ^5.0.1
  
  # Authentication
  crypto: ^3.0.3
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Video Player
  video_player: ^2.8.1
  
  # File Handling
  file_picker: ^6.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Social Media
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  
  # Analytics
  firebase_analytics: ^10.7.4
  
  # Charts
  fl_chart: ^0.66.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Rich Text Editor
  flutter_quill: ^9.3.1
  
  # Animation
  animated_text_kit: ^4.2.2
  
  # Platform specific
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21